version: '3.8'
services:
  agent:
    image: portainer/agent
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    restart: unless-stopped

  portainer:
    image: portainer/portainer
    command: -H tcp://agent:9001 --tlsskipverify
    volumes:
      - data:/data
    restart: unless-stopped
    depends_on:
      - agent

volumes:
  data:
networks:
  default:
    external: true
    name: services